#include "variant.h"

const PinDescription g_APinDescription[]=
{
  // Digital 0..5 (display)
  { PORTB, 0, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_0 },	// 0.DB4
  { PORTB, 1, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_1 },	// 1.DB5
  { PORTB, 2, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_2 },	// 2.DB6
  { PORTB, 3, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3 },	// 3.DB7
  { PORTB, 30, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER,EXTERNAL_INT_14 },	// 4.RS
  { PORTB, 31, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_15 },	// 5.E

  // Digital 6..9 (Vol/Freq)
  { PORTA, 20, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_4 },	// 6.Vol+
  { PORTA, 21, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_5 },	// 7.Vol-
  { PORTA, 23, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6 },	// 8.Freq+
  { PORTA, 24, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_7 },	// 9.Freq-

  // I2C 10..12
  { PORTB, 12, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_12 },	// 10.SDA
  { PORTB, 13, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_13 },	// 11.SCL
  { PORTB, 14, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_14 },	// 12.SEN

  // Digital 13..15 (Si4730)
  { PORTA, 13, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_13 },	// 13.GPO3
  { PORTA, 14, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_14 },	// 14.GPO2
  { PORTA, 15, PIO_DIGITAL, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_15 },	// 15.GPO1

  // SPI 16..19
  { PORTA, 4, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_4 },		// 16.SCK
  { PORTA, 5, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_5 },		// 17.MISO
  { PORTA, 6, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6 },		// 18.CS
  { PORTA, 7, PIO_SERCOM, PIN_ATTR_DIGITAL, NO_ADC_CHANNEL, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_7 },		// 19.MOSI

  // Analog 20..22
  { PORTB, 8, PIO_ANALOG, PIN_ATTR_ANALOG, ADC_Channel2, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_8 },		// 20.ROUT
  { PORTB, 9, PIO_ANALOG, PIN_ATTR_ANALOG, ADC_Channel2, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_9 },		// 21.LOUT
  { PORTA, 3, PIO_ANALOG, PIN_ATTR_ANALOG, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, 	// 22.AREF

  // USB 23..25
  { PORTA, 28, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, 		// 23.USB Host enable
  { PORTA, 24, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, 		// 24.USB/DM
  { PORTA, 25, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, 		// 25.USB/DP
} ;

extern "C" {
    unsigned int PINCOUNT_fn() {
        return (sizeof(g_APinDescription) / sizeof(g_APinDescription[0]));
    }
}

const void* g_apTCInstances[TCC_INST_NUM + TC_INST_NUM]={ TCC0, TCC1, TCC2, TC3, TC4, TC5 } ;

// Multi-serial objects instantiation
SERCOM sercom0( SERCOM0 ) ;
SERCOM sercom1( SERCOM1 ) ;
SERCOM sercom2( SERCOM2 ) ;
SERCOM sercom3( SERCOM3 ) ;
SERCOM sercom4( SERCOM4 ) ;
SERCOM sercom5( SERCOM5 ) ;

// Uart Serial1( &sercom0, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX ) ;
// Uart Serial( &sercom5, PIN_SERIAL_RX, PIN_SERIAL_TX, PAD_SERIAL_RX, PAD_SERIAL_TX ) ;
// void SERCOM0_Handler()
// {
//   Serial1.IrqHandler();
// }

// void SERCOM5_Handler()
// {
//   Serial.IrqHandler();
// }

